### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by kisyular** [kisyular/MI-449-SS17-740-html-semantic-elements-5BSgA-#1]
@egillespie Can you take a look at this? It's [hosted here](https://kisyular.github.io/MI-449-SS17-740-html-semantic-elements-5BSgA-/) and meets the following criteria:

- [x] Place a `nav` element at the top of the page that includes (fake) links to other pages
- [x] Use the `main` element appropriately
- [x] Include three products your store sells, all listed on the same Products page
- [x] For each product, correctly use an `article`, `header`, and `footer` element
- [x] Use `figure` and `figcaption` to show what each product looks like
- [x] Each product includes a `nav` element with one or more links to related products (the links don't have to go anywhere)
- [x] Use an `aside` in one or more products to advertise a promotion or discount for that product

**Comment by egillespie** [comment]
Niiiiiice! ✊  It looks like you've really latched onto how semantic elements are used and overall I really like the structure of the page.

I just have a couple of minor requests:

### Move last `nav` into `article`

It looks like this may have been a copy-paste error, but could you move the last `nav` element inside the `article` that it's next to? Putting navigation elements inside the articles is a great way to let search engines know which other pages on your site have something in common with other articles.

### Remove `class=""`

This is called "dead code" because it's not doing anything except taking up space. It's better to remove dead code because there's always a chance that a change could cause the code to come alive and start breaking things. a.k.a. zombie code ☠️ 

---

After you’ve made your changes and pushed them to GitHub and your hosted site, give it a once-over to make sure it looks right, then comment back here and I’ll take another look.

Thanks! :rocket:

**Comment by kisyular** [comment]
@egillespie, I have moved the `nav` tag into `article` tag and removed the `zombie code`
Kindly take a look

**Comment by egillespie** [comment]
Perfecto! 👏  :shipit:
